import React from 'react';

export const Disclaimer: React.FC = () => {
  return (
    <div 
      className="disclaimer-banner"
      role="note"
      aria-label="Legal disclaimer"
    >
      <span className="warning-icon">⚠️</span>
      <p>
        This analysis is provided for informational purposes only and does not constitute legal advice. The findings are generated by an AI system and may not capture all relevant legal nuances. Consult a qualified legal professional before making decisions based on this analysis. The system does not determine which document provisions are legally controlling.
      </p>
    </div>
  );
};
